---
nginx_configs:
  upstream:
    - upstream swarm_http {
      {% for h in groups['swarm'] %}
      server {{ hostvars[h].ansible_host }}:{{ swarm_port }};
      {% endfor %}
      }

nginx_sites:
  swarm_lb:
    - listen 8443 ssl

    - server_name {{ env }}-{{ stage }}.status.im

    - ssl_certificate     /certs/origin.crt
    - ssl_certificate_key /certs/origin.key

    - client_max_body_size 64k

    - location / {
        proxy_pass http://swarm_http;
      }
