---
nginx_sites:
  default:
    - listen 443 ssl default_server

    - server_name _

    - ssl_certificate     /certs/origin.crt
    - ssl_certificate_key /certs/origin.key

    - client_max_body_size 10m

    - location / {
        proxy_pass http://localhost:{{ swarm_http }};
      }
