---
swarm_cont_version: '0.5.7-alltools'
swarm_cont_image: 'ethersphere/swarm:{{ swarm_cont_version }}'
swarm_cont_name: 'swarm-node'
swarm_cont_vol: '/docker/{{ swarm_cont_name }}'
# listen port which will be incremented for every dontainer
swarm_cont_port: 30399 
# address to listen on
swarm_cont_addr: '0.0.0.0'

# main http port
swarm_addr: '0.0.0.0'
swarm_http_port: 8180
swarm_ssl: 8443
# 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail
swarm_log_lvl: 3

# storage limits (bytes)
swarm_chunk_size: 5000
# roughly 25GB
swarm_store_size: 5000000
swarm_store_cache_size: 5000

# Geth container info
swarm_geth_account: ~
swarm_geth_cont_name: ~
swarm_geth_cont_vol: ~
swarm_geth_rcp_port: ~

# Generic container options
cont_state: started
cont_recreate: false
cont_restart: false
