---
cont_image: 'ethdevops/swarm:latest'
cont_name: 'swarm-node'
cont_state: started
cont_recreate: false
cont_restart: false

cont_vol: '/docker/{{ cont_name }}'

# listen port which will be incremented for every dontainer
cont_port: 30399 
# address to listen on
cont_addr: '0.0.0.0'

# Geth settings
geth_image: 'ethdevops/geth:v1.8.14'
geth_name: 'swarm-geth'
geth_vol: '/docker/{{ geth_name }}'
geth_keys: '{{ geth_vol }}/keys'
geth_port: 30303
geth_rpc_addr: '0.0.0.0'
geth_rpc_port: 8545
# account to use for swarm
geth_pass: ~
geth_account: ~

# main http port
swarm_addr: '0.0.0.0'
swarm_port: 8080
swarm_ssl: 8443

# for key generation
genkey_image: 'ethereum/client-go:alltools-latest'
