---
- name: Find all enode files
  find:
    paths: '{{ geth_keys }}'
    patterns: 'UTC--*'
    file_type: file
  register: account_files

- name: Set Geth password to be empty
  copy:
    dest: '{{ geth_keys }}/password'
    content: ''

- name: Generate Geth account
  docker_container:
    name: '{{ geth_name }}-acc-gen'
    image: '{{ geth_image }}'
    user: root
    pull: true
    auto_remove: yes
    entrypoint: '/usr/local/bin/geth'
    command: |
      account new
      --keystore=/keys
      --password=/keys/password
    volumes:
      - '{{ geth_vol }}/keys:/keys:rw'
  when: account_files.files | length == 0
  register: dbg

- name: Find all enode files
  find:
    paths: '{{ geth_keys }}'
    patterns: 'UTC--*'
    file_type: file
  register: account_files

- name: Read account addres
  shell: 'cat {{ account_files.files[0].path }} | jq -r .address'
  register: account_address

- name: Save geth account address
  set_fact:
    geth_account: '{{ account_address.stdout }}'
