- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ swarm_cont_name }}'
    consul_services:
      - id: '{{ swarm_cont_name }}'
        name: '{{ swarm_cont_name }}'
        port: '{{ swarm_cont_port }}'
        tags: ['{{ env }}.{{ stage }}', 'swarm']
