---
- name: Enable swarm ports
  iptables:
    comment: '{{ item.name }}'
    action: insert
    chain: DOCKER-USER
    jump: ACCEPT
    source: '0.0.0.0/0'
    protocol: '{{ item.proto }}'
    destination_port: '{{ item.port }}'
  with_items:
    - { 'name': 'Swarm',       'port': '{{ cont_port }}',  'proto': 'udp' }
    - { 'name': 'Swarm HTTP',  'port': '{{ swarm_http_port }}', 'proto': 'tcp' }
  notify:
    - Save iptables rules
