---
- name: Run Geth container
  docker_container:
    name: '{{ geth_name }}'
    image: '{{ geth_image }}'
    user: root
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    entrypoint: '/geth'
    # enable image updates via watchtower
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    ports:
      - '{{ geth_port }}:{{ geth_port }}'
      - '{{ geth_rpc_port }}:{{ geth_rpc_port }}'
    command: |
      --testnet
      --syncmode=light
      --datadir=/data
      --keystore=/keys
      --port={{ geth_port }}
      --rpc
      --rpcaddr={{ geth_rpc_addr }}
      --rpcport={{ geth_rpc_port }}
      --rpcapi=db,eth,net,web3,admin
    volumes:
      - '{{ geth_vol }}/keys:/keys:rw'
      - '{{ geth_vol }}/data:/data:rw'

- name: Enable geth port
  iptables:
    comment: '{{ geth_name }}'
    chain: INPUT
    jump: ACCEPT
    source: '0.0.0.0/0'
    protocol: udp
    destination_port: '{{ geth_port }}'
  notify:
    - Save iptables rules
