---
- name: Create directories for Swarm
  file:
    path: '{{ item }}'
    state: directory
    owner: dockremap
    recurse: true
  with_items:
    - '{{ swarm_cont_vol }}/data'
    - '{{ swarm_cont_vol }}/store'

- include_tasks: firewall.yml
- include_tasks: swarm.yml
- include_tasks: consul.yml
