---
- name: Start Swarm container
  docker_container:
    name: '{{ swarm_cont_name }}'
    image: '{{ swarm_cont_image }}'
    user: root
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    # enable image updates via watchtower
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    ports:
      - '{{ swarm_cont_port }}:{{ swarm_cont_port }}'
      - '127.0.0.1:{{ swarm_http_port }}:8500'
    links:
      - '{{ swarm_geth_cont_name | mandatory }}:geth'
    command: |
      --verbosity={{ swarm_log_lvl }}
      --port={{ swarm_cont_port }}
      --httpaddr={{ swarm_addr }}
      --bzzaccount={{ swarm_geth_account | mandatory }}
      --datadir=/data
      --keystore=/keys
      --password=/keys/account.pass
      --store.path=/store
      --store.size={{ swarm_store_size }}
      --store.cache.size={{ swarm_store_cache_size }}
      --corsdomain='*'
      --ens-api=http://geth:{{ swarm_geth_rcp_port | mandatory }}
    volumes:
      - '{{ swarm_geth_cont_vol | mandatory }}/keys:/keys:rw'
      - '{{ swarm_cont_vol }}/data:/data:rw'
      - '{{ swarm_cont_vol }}/store:/store:rw'
