---
- name: Run Swarm container
  docker_container:
    name: '{{ cont_name }}'
    image: '{{ cont_image }}'
    user: root
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    entrypoint: '/swarm'
    # enable image updates via watchtower
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    ports:
      - '{{ cont_port }}:{{ cont_port }}'
      - '127.0.0.1:{{ swarm_http_port }}:8500'
    links:
      - '{{ geth_name }}:geth'
    command: |
      --verbosity="{{ swarm_log_lvl }}"
      --port={{ cont_port }}
      --httpaddr={{ swarm_addr }}
      --bzzaccount={{ geth_account }}
      --datadir=/data
      --keystore=/keys
      --password=/keys/password
      --store.path=/store
      --store.size={{ swarm_store_size }}
      --store.cache.size={{ swarm_store_cache_size }}
      --corsdomain='*'
      --ens-api='http://geth:{{ geth_rpc_port }}'
    volumes:
      - '{{ geth_vol }}/keys:/keys:rw'
      - '{{ cont_vol }}/data:/data:rw'
      - '{{ cont_vol }}/store:/store:rw'
