---
- name: Configure swarm
  hosts: swarm
  roles:
    - { role: origin-certs,    tags: origin-certs }
    - { role: nginx,           tags: nginx }
    - { role: infra-role-geth, tags: infra-role-geth }
    - { role: swarm,           tags: swarm }
